# Generated by Django 5.2.3 on 2025-06-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributestrengthmap',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
