# Generated by Django 5.2.3 on 2025-06-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0002_attributestrengthmap_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributestrengthmap',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributestrengthmap',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
